runtime: custom
env: flex
service: vscapnew

beta_settings:
  cloud_sql_instances: capsum-project-292904:us-central1:capsum-sql

manual_scaling:
  instances: 1
resources:
  cpu: 8
  memory_gb: 8
  disk_size_gb: 25
